### ISSUE TITLE
Clippy is missing in integrations tests

### ISSUE THREAD

**Issue by Horki** [mgattozzi/ferris-says#16]
@mgattozzi Hi, I have added "clippy" feature in integrations tests, please check #15

**Comment by Horki** [comment]
@mgattozzi PS, I could also update `.travis.yml` for clippy feature

**Comment by Horki** [comment]
@mgattozzi should I close this?

**Comment by mgattozzi** [comment]
Ah no need to close I'm just not great at following up on my oss projects unless I get directly pinged which gives me a phone notification. I'll take a look now!
