### ISSUE TITLE
Release new version and publish it to crates.io

### ISSUE THREAD

**Issue by aleksanderkrauze** [mgattozzi/ferris-says#34]
#21 fixed unsoundness bug, but version on crates.io still uses old vulnerable code. Please release current code as a `0.2.2` and consider yanking affected versions.

Also I created #32 and #33, which (if accepted) should be released as `0.3` (since they break API).

**Comment by mgattozzi** [comment]
I messed up but it's published now https://crates.io/crates/ferris-says/0.3.1

I'm not gonna do a PR to the website since doing all this took a lot out of me but you're more than welcome too.

**Comment by aleksanderkrauze** [comment]
Thanks. I'll do that.

But now `README` is out of date (and readme on crates.io). Will you fix it, or should I make a PR?
