### ISSUE TITLE
Example run wrong

### ISSUE THREAD

**Issue by GOWxx** [mgattozzi/ferris-says#35]
enviroments: macOs 13 Ventura
```bash
% rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.65.0 (897e37553 2022-11-02)`

% cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```
run wrong with
```rs
  let out = b"Hello fellow Rustaceans!"; // now, type of out is '&[u8; 24]'
  say(input: &str)
```
<img width="717" alt="image" src="https://user-images.githubusercontent.com/12870715/200044162-e9cb929e-4a3c-4f64-864b-f2f68637af2f.png">

`cargon run` get an error.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/12870715/200044273-60074fdd-46d2-498c-8692-1e5f5928502d.png">

**Comment by gitSirzh** [comment]
![image](https://user-images.githubusercontent.com/34081633/204234921-e1e7fede-ad7b-42de-999b-36ecf02e6c84.png)

**Comment by thoroc** [comment]
Don't forget the type:
```rust
let out &str = "Hello fellow Rustaceans!";
```
