### ISSUE TITLE
clippy variant

### ISSUE THREAD

**Issue by llogiq** [mgattozzi/ferris-says#4]
Can we have a variant with clippy instead of ferris?

**Comment by mgattozzi** [comment]
@llogiq for the clippy library yeah? I think that should be doable.

**Comment by llogiq** [comment]
Great! Now someone needs to add an easter-egg mode for clippy. I've submitted an issue.

**Comment by mgattozzi** [comment]
I'll merge it then and do a small release with it as part of it.
