### ISSUE TITLE
Publish new release to crates.io

### ISSUE THREAD

**Issue by senekor** [mgattozzi/ferris-says#58]
We got a few issues (not that many) of people new to Rust on [rust-lang/www.rust-lang.org](https://github.com/rust-lang/www.rust-lang.org). The problem is that the readme on [crates.io](https://crates.io/crates/ferris-says) still suggests putting version `0.2` in Cargo.toml. Consider publishing a new release, so the readme is up to date.

**Comment by lcnr** [comment]
done!
