### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by Diggsey** [mgattozzi/ferris-says#6]
Hey, just wondering if this is the same ASCII art that I made:
https://www.reddit.com/r/rust/comments/52vb6y/animated_ferris_the_rustacean/d7phkyh/

**Comment by mgattozzi** [comment]
I believe I did when I looked up ASCII ferris. Let me add you as a source for the original to the README!

**Comment by mgattozzi** [comment]
@Diggsey I made sure to give you credit now. Apologies for that! If you would prefer a different illustration done out and not yours, let me know and I'm more than happy to remove it from the crate, yank older versions, and update it with a different one. If the credit is enough also let me know! I would hate to have done this without realizing the implications and am willing to remedy it if that's the case!

**Comment by Diggsey** [comment]
No worries, I'm just happy to see it used 😄

**Comment by mgattozzi** [comment]
Awesome! :D I'm glad. It definitely was good to have it there for my rustconf talk last year. It was less work I had to do because I am definitely not an artist let alone an ASCII one :laughing:
