### ISSUE TITLE
Add additional speech modes

### ISSUE THREAD

**Issue by spacekookie** [mgattozzi/ferris-says#7]
Optionally make it possible for Ferris to think (with `o O` bubbles) or to shout (by using `/ \` for the speech bubble), similar to what `cowsay` and `cowthink` do.

**Comment by mgattozzi** [comment]
Oh that would be neat! I'm a bit busy with the wasm working group and my personal life right now but I'm more than willing to point out what needs to be done to get that working if anyone is interested
